# Generated by Django 5.0.2 on 2024-02-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('atm_pressure', models.FloatField(blank=True, default=None, null=True)),
                ('humidity', models.FloatField(blank=True, default=None, null=True)),
                ('temperature_average', models.FloatField(blank=True, default=None, null=True)),
                ('temperature_infrared', models.FloatField(blank=True, default=None, null=True)),
                ('illuminance', models.FloatField(blank=True, default=None, null=True)),
                ('wind_dir_numeric', models.IntegerField(blank=True, default=None, null=True)),
                ('wind_speed', models.FloatField(blank=True, default=None, null=True)),
                ('power_supply', models.FloatField(blank=True, default=None, null=True)),
                ('battery_voltage', models.FloatField(blank=True, default=None, null=True)),
                ('gps_status', models.BooleanField(blank=True, default=None, null=True)),
                ('gps_longitude', models.FloatField(blank=True, default=None, null=True)),
                ('gps_latitude', models.FloatField(blank=True, default=None, null=True)),
                ('gps_altitude', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Controller Data',
                'verbose_name_plural': 'Controller Data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
